/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针（SQLite + blob 目录自检通过后才返回 200） */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 运行时状态（版本、就绪、迁移版本、初始化标志、用户数） */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/replication-apply-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 复制接收审计记录（仅管理员） */
        get: operations["getReplicationApplyLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 首启管理员自举（仅在未初始化，即 user 表为空时可用） */
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户名 + 口令换取会话 JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注销当前会话（当前 JWT 记入吊销名单直至过期） */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表（分页） */
        get: operations["listUsers"];
        put?: never;
        /** 创建用户 */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** 更新用户（角色 / 状态） */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改 / 重置用户口令 */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户的 API Token 列表（不含明文） */
        get: operations["listTokens"];
        put?: never;
        /** 签发 API Token（明文仅此次返回一次） */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 吊销 API Token */
        delete: operations["deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 仓库列表（分页，按可见性 / ACL 过滤） */
        get: operations["listRepositories"];
        put?: never;
        /** 创建仓库 */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除仓库 */
        delete: operations["deleteRepository"];
        options?: never;
        head?: never;
        /** 更新仓库（可见性 / 配置） */
        patch: operations["updateRepository"];
        trace?: never;
    };
    "/api/v1/repositories/{name}/acl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取仓库 ACL */
        get: operations["getRepositoryAcl"];
        /** 覆盖写入仓库 ACL */
        put: operations["setRepositoryAcl"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 设置仓库 online/offline 状态（仅管理员）
         * @description 仅管理员可操作。online 是节点本地运维状态：不参与复制（M-2），
         *     对端复制应用仓库变更不会覆盖本地 online，SetOnline 亦不产生复制变更日志。
         */
        put: operations["setRepositoryOnline"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}/recheck-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手动重测仓库上游连接（仅管理员）
         * @description 仅管理员可操作；仅 online 的 proxy 仓库可重测。立即发起一次上游 HEAD 探测，
         *     更新 auto-block 状态并返回最新连接状态（不等待自动阻止窗口）。
         */
        post: operations["recheckRepositoryConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出仓库制品（分页，可按路径前缀过滤） */
        get: operations["listRepositoryAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}/assets/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量删除仓库制品（仅管理员）
         * @description 对每个 path 复用单条删除语义（元数据删 + 复制 tombstone）并逐条写 asset.delete 审计。
         *     逐条尽力：部分失败进入 failed 明细，不做整体回滚。
         */
        post: operations["batchDeleteRepositoryAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{name}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 仓库客户端使用片段（据 format/type 返回接入命令） */
        get: operations["getRepositoryUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 三来源发现并落库为 planned 任务（不同步执行）
         * @description 同步执行发现；成功写入一条 status=planned 的 migration_task，返回 taskId 与 plan。
         *     失败不落库。真正搬运须 POST /migrations/{id}/start。仅 admin。
         */
        post: operations["discoverMigrations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 迁移任务列表（分页） */
        get: operations["listMigrations"];
        put?: never;
        /** 创建 planned 迁移任务（不自动执行） */
        post: operations["createMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 迁移任务详情 */
        get: operations["getMigration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 显式启动（planned → running）
         * @description 可选 body.includeRepositories：启动前收窄 plan，仅迁移选中仓库（在线/离线均适用）。
         *     省略或空数组表示按当前 plan 全部仓库执行。
         */
        post: operations["startMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 自 failed/cancelled 断点续传 */
        post: operations["resumeMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消 planned 或协作取消 running */
        post: operations["cancelMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 迁移报告 */
        get: operations["getMigrationReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/migrations/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 切换窗口最终增量扫描（仅 completed）
         * @description 对同一来源再枚举，仅复制目标不存在的路径；更新 report.delta。
         */
        post: operations["finalizeMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            version: string;
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        ReplicationApplyLog: {
            sourceNode: string;
            /** Format: int64 */
            sourceSeq: number;
            peerUrl: string;
            entityType: string;
            entityKey: string;
            op: string;
            /** @enum {string} */
            result: "applied" | "metadata_applied_pending_blob" | "lww_skipped" | "pending_parent" | "blob_failed" | "skipped_permanent" | "failed";
            detail: string;
            lastError?: string;
            lastErrorAt?: string;
            firstSeenAt: string;
            lastSeenAt: string;
            attemptCount: number;
        };
        ReplicationApplyLogList: {
            items: components["schemas"]["ReplicationApplyLog"][];
            total: number;
        };
        StatusInfo: {
            version: string;
            ready: boolean;
            initialized: boolean;
            migrationVersion: string;
            userCount: number;
        };
        BootstrapRequest: {
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** @enum {string} */
            status: "active" | "disabled";
            createdAt: string;
        };
        UserList: {
            items: components["schemas"]["User"][];
            total: number;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        UpdateUserRequest: {
            /** @enum {string} */
            role?: "admin" | "user";
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        PasswordChangeRequest: {
            password: string;
        };
        Token: {
            /** Format: int64 */
            id: number;
            name: string;
            createdAt: string;
        };
        TokenList: {
            items: components["schemas"]["Token"][];
        };
        CreateTokenRequest: {
            name: string;
        };
        TokenCreated: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description 明文令牌，仅此次返回一次。 */
            token: string;
            createdAt: string;
        };
        Repository: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            format: "raw" | "maven" | "npm";
            /** @enum {string} */
            type: "hosted" | "proxy" | "group";
            /** @enum {string} */
            visibility: "public" | "private";
            /** @description 仓库是否在线（管理员可手动置离线；offline 不参与复制） */
            online?: boolean;
            /** @description 上游连接状态（仅 proxy/group 返回；可选字段，向后兼容） */
            connectionStatus?: components["schemas"]["ConnectionStatus"];
            /** @description 仓库描述（管理后台可配置，详情页展示） */
            description?: string;
            /** @description proxy 仓库的上游地址（仅 type=proxy） */
            remoteUrl?: string;
            /** @description group 仓库的成员仓库名（有序，仅 type=group） */
            members?: string[];
            createdAt: string;
            /** @description 仓库内制品数量（只读统计字段） */
            artifactCount?: number;
            /**
             * Format: int64
             * @description 仓库内制品总字节数（只读统计字段）
             */
            totalSize?: number;
        };
        RepositoryList: {
            items: components["schemas"]["Repository"][];
            total: number;
        };
        CreateRepositoryRequest: {
            name: string;
            /** @enum {string} */
            format: "raw" | "maven" | "npm";
            /** @enum {string} */
            type: "hosted" | "proxy" | "group";
            /**
             * @default private
             * @enum {string}
             */
            visibility: "public" | "private";
            /** @description 仓库描述（可选） */
            description?: string;
            /** @description proxy 仓库的上游地址（type=proxy 时必填） */
            remoteUrl?: string;
            /** @description group 仓库的成员仓库名（有序，type=group 时必填） */
            members?: string[];
        };
        UpdateRepositoryRequest: {
            /** @enum {string} */
            visibility?: "public" | "private";
            /** @description 更新仓库描述（传空串表示清空） */
            description?: string;
            /** @description 更新 proxy 上游地址（仅 type=proxy） */
            remoteUrl?: string;
            /** @description 更新 group 成员仓库名（仅 type=group） */
            members?: string[];
        };
        SetRepositoryOnlineRequest: {
            /** @description 是否在线（true=在线，false=离线；必填） */
            online?: boolean;
        };
        ConnectionStatus: {
            /**
             * @description 上游连接状态（READY=尚未探测，AVAILABLE=可用，AUTO_BLOCKED=自动阻止，UNAVAILABLE=不可用，OFFLINE=手动离线）
             * @enum {string}
             */
            status: "READY" | "AVAILABLE" | "UNAVAILABLE" | "AUTO_BLOCKED" | "OFFLINE";
            /**
             * Format: date-time
             * @description 自动阻止窗口截止时间（非阻止状态为 null）
             */
            blockedUntil?: string | null;
            /** @description 状态说明（供展示） */
            description?: string;
        };
        AclEntry: {
            /** Format: int64 */
            subjectId: number;
            /** @enum {string} */
            action: "read" | "write" | "admin";
        };
        AclList: {
            items: components["schemas"]["AclEntry"][];
        };
        PutAclRequest: {
            items: components["schemas"]["AclEntry"][];
        };
        AssetSummary: {
            path: string;
            /** Format: int64 */
            size: number;
            /** @description 内容寻址 blob 的 sha256 摘要 */
            hash: string;
            /** @description 制品内容的 SHA-1 摘要（写入时计算登记） */
            sha1?: string;
            /** @description 制品内容的 MD5 摘要（写入时计算登记） */
            md5?: string;
            contentType?: string;
            /** @description 首次写入时间 */
            createdAt?: string;
            updatedAt: string;
        };
        AssetList: {
            items: components["schemas"]["AssetSummary"][];
            total: number;
        };
        BatchDeleteAssetsRequest: {
            /** @description 待删除的制品路径列表（单条非空，上限 500 条） */
            paths: string[];
        };
        BatchDeleteAssetFailure: {
            path: string;
            error: string;
        };
        BatchDeleteAssetsResponse: {
            /** @description 成功删除的制品数 */
            deleted: number;
            /** @description 删除失败的路径与原因明细（成功数不受其影响） */
            failed: components["schemas"]["BatchDeleteAssetFailure"][];
        };
        UsageSnippet: {
            title: string;
            description?: string;
            code: string;
        };
        UsageInfo: {
            format: string;
            type: string;
            /** @description 仓库描述（匿名详情页页头展示） */
            description?: string;
            snippets: components["schemas"]["UsageSnippet"][];
        };
        /** @enum {string} */
        MigrationSourceType: "online_rest" | "offline_dir" | "offline_bundle";
        /**
         * @default skip
         * @enum {string}
         */
        MigrationConflictPolicy: "skip" | "overwrite" | "fail";
        /** @enum {string} */
        MigrationTaskStatus: "planned" | "running" | "completed" | "failed" | "cancelled";
        /** @description 来源配置（url/path 等），不得含密钥明文 */
        MigrationSourceConfig: {
            [key: string]: unknown;
        };
        MigrationPlanRepository: {
            name: string;
            /** @enum {string} */
            format: "raw" | "maven" | "npm";
            /** @enum {string} */
            type?: "hosted" | "proxy" | "group";
            /** Format: int64 */
            estimatedAssets?: number;
        };
        MigrationPlan: {
            repositories: components["schemas"]["MigrationPlanRepository"][];
            warnings: string[];
            stats: {
                [key: string]: unknown;
            };
            /** @description 资产数是否为估算 */
            estimated?: boolean;
        };
        MigrationTask: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["MigrationTaskStatus"];
            sourceType: components["schemas"]["MigrationSourceType"];
            sourceConfig?: components["schemas"]["MigrationSourceConfig"];
            /** @description 环境变量引用名，非密钥明文 */
            credentialRef?: string;
            conflictPolicy: components["schemas"]["MigrationConflictPolicy"];
            plan?: components["schemas"]["MigrationPlan"];
            errorMessage?: string;
            createdAt: string;
            updatedAt: string;
            startedAt?: string;
            finishedAt?: string;
        };
        MigrationTaskList: {
            items: components["schemas"]["MigrationTask"][];
            total: number;
        };
        CreateMigrationRequest: {
            sourceType: components["schemas"]["MigrationSourceType"];
            sourceConfig?: components["schemas"]["MigrationSourceConfig"];
            credentialRef?: string;
            conflictPolicy?: components["schemas"]["MigrationConflictPolicy"];
            plan?: components["schemas"]["MigrationPlan"];
        };
        StartMigrationRequest: {
            /** @description 启动前收窄 plan，仅迁移这些仓库；空或省略表示全部 */
            includeRepositories?: string[];
        };
        MigrationDiscoverRequest: {
            sourceType: components["schemas"]["MigrationSourceType"];
            sourceConfig?: components["schemas"]["MigrationSourceConfig"];
            credentialRef?: string;
            conflictPolicy?: components["schemas"]["MigrationConflictPolicy"];
        };
        MigrationDiscoverResponse: {
            /** Format: int64 */
            taskId: number;
            plan: components["schemas"]["MigrationPlan"];
        };
        MigrationReport: {
            /** Format: int64 */
            taskId: number;
            status: components["schemas"]["MigrationTaskStatus"];
            sourceType?: components["schemas"]["MigrationSourceType"];
            conflictPolicy?: components["schemas"]["MigrationConflictPolicy"];
            startedAt?: string;
            finishedAt?: string;
            totals: {
                [key: string]: unknown;
            };
            repositories?: {
                [key: string]: unknown;
            }[];
            failures?: {
                [key: string]: unknown;
            }[];
            warnings?: string[];
            cutover?: {
                [key: string]: unknown;
            };
            /** @description 任务 report_json 原文透传（foundation 可为空对象） */
            raw?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 越权 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PageParam: number;
        PageSizeParam: number;
        UserIdParam: number;
        TokenIdParam: number;
        RepoNameParam: string;
        MigrationIdParam: number;
        /** @description 按制品路径前缀过滤 */
        PrefixParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description 未就绪 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 状态信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusInfo"];
                };
            };
        };
    };
    getReplicationApplyLogs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sourceNode?: string;
                sourceSeq?: number;
                peerURL?: string;
                entityType?: string;
                entityKey?: string;
                op?: string;
                result?: "applied" | "metadata_applied_pending_blob" | "lww_skipped" | "pending_parent" | "blob_failed" | "skipped_permanent" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 复制接收审计分页结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplicationApplyLogList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description 首个管理员创建成功，返回会话 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 实例已初始化，自举关闭 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已注销 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description 已修改 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 令牌列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description 已签发 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCreated"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TokenIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已吊销 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRepositories: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仓库列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRepositoryRequest"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getRepositoryAcl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ACL 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AclList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setRepositoryAcl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutAclRequest"];
            };
        };
        responses: {
            /** @description 已写入 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AclList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setRepositoryOnline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRepositoryOnlineRequest"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    recheckRepositoryConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重测完成，返回最新连接状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRepositoryAssets: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
                /** @description 按制品路径前缀过滤 */
                prefix?: components["parameters"]["PrefixParam"];
            };
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 制品列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    batchDeleteRepositoryAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteAssetsRequest"];
            };
        };
        responses: {
            /** @description 批量删除结果（部分失败以 failed 明细返回） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteAssetsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getRepositoryUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["RepoNameParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 使用片段 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    discoverMigrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationDiscoverRequest"];
            };
        };
        responses: {
            /** @description 发现成功并已落库 planned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationDiscoverResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 上游 Nexus 不可达 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listMigrations: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTaskList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createMigration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigrationRequest"];
            };
        };
        responses: {
            /** @description 已创建 planned 任务 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMigration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startMigration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartMigrationRequest"];
            };
        };
        responses: {
            /** @description 已进入 running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeMigration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已恢复 running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelMigration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getMigrationReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 结构化报告 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeMigration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MigrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 增量完成，返回任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationTask"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
